name: Composite Action
description: A composite action to build Laravel applications
inputs:
  node-version:
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }} # or the version you are using

    - name: Install dependencies
      run: npm install
      shell: bash
        
