name: "Build Reusable Workflow For Laravel app"

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
jobs:
  build:
    name: Build Next App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout php
        uses: actions/checkout@v4

      - uses: Verdent-Sphere-Thiha-Zaw/thz_verdant_sphere_landing_app/.github/prepare-action@VSLP-01

      - name: Build the app
        run: |
          npm run build

