name: "CI Workflow"
on:
    pull_request:
      types: [opened, synchronize, reopened]
    push:
      branches:
        - VSLP-01
        - main
permissions:
  checks: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  # build:
  #   name: Build
  #   uses: Verdent-Sphere-Thiha-Zaw/thz_verdant_sphere_landing_app/.github/workflows/build.yaml@VSLP-01
  #   with:
  #     node-version: '20'

  # test:
  #   name: Test
  #   needs: [build]
  #   uses: Verdent-Sphere-Thiha-Zaw/thz_verdant_sphere_landing_app/.github/workflows/test.yaml@VSLP-01
  #   with:
  #     node-version: '20'

  sec:
    name: Sec Check
    # needs: [test]
    uses: ./.github/workflows/security.yaml
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # release:
  #   name: Release
  #   needs: [test]
  #   uses: Verdent-Sphere-Thiha-Zaw/thz_verdant_sphere_landing_app/.github/workflows/release.yaml@VSLP-01
  #   with:
  #     node-version: '20'

#   push:
#     name: Push
#     needs: [test]
#     uses: Verdent-Sphere-Thiha-Zaw/thz_verdant_sphere_landing_app/.github/workflows/push.yaml@VSLP-01
#     secrets:
#       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#       DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

#   deploy:
#     name: Deploy
#     needs: [push]
#     uses: Verdent-Sphere-Thiha-Zaw/thz_verdant_sphere_landing_app/.github/workflows/deploy.yaml@VSLP-01
#     secrets:
#       KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

