name: "Release Next App"

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  release:
    name: release Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore the cache
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-app

      - name: Build the app
        run: npm run build

      - name: Upload the artifacts
        uses: actions/upload-artifact@v4    
        with:
          name: my-artifacts
          path: .next