name: "Test Next App"

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  build:
    name: Testing Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout php
        uses: actions/checkout@v4

      - name: Restore the cache
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: ./vendor
          key: next-app

      - name: Node install
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or the version you are using

      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Test the App
        run: npm test